import { NextRequest, NextResponse } from 'next/server';

// Simple dictionary for common Spanish to English translations
// In a real app, you would use a proper translation API like Google Translate
const translations: Record<string, string> = {
  // Store names
  'maxipali': 'MaxiPali',
  'automercado': 'Auto Mercado',
  'masxmenos': 'Mas x Menos',
  'pricesmart': 'PriceSmart',
  'walmart': 'Walmart',
  'pequeño mundo': 'Pequeño Mundo',
  'universal': 'Universal',
  'perimercados': 'Perimercados',
  'mega super': 'Mega Super',

  // Product categories
  'abarrotes': 'groceries',
  'bebidas': 'beverages',
  'lácteos': 'dairy',
  'carnes': 'meats',
  'frutas y verduras': 'fruits and vegetables',
  'panadería': 'bakery',
  'limpieza': 'cleaning',
  'cuidado personal': 'personal care',
  'hogar': 'home',
  'mascotas': 'pets',
  'bebés': 'babies',
  'electrónicos': 'electronics',
  'ropa': 'clothing',
  'juguetes': 'toys',
  'deportes': 'sports',
  'ferretería': 'hardware',
  'jardín': 'garden',
  'automotriz': 'automotive',
  'farmacia': 'pharmacy',
  'licores': 'liquor',
  'congelados': 'frozen',
  'snacks': 'snacks',
  'dulces': 'candy',
  'orgánicos': 'organic',
  'sin gluten': 'gluten-free',
  'vegano': 'vegan',
  'vegetariano': 'vegetarian',
  'sin azúcar': 'sugar-free',
  'sin lactosa': 'lactose-free',
  'bajo en sodio': 'low sodium',
  'bajo en grasa': 'low fat',
  'alto en proteína': 'high protein',
  'importado': 'imported',
  'nacional': 'national',
  'oferta': 'sale',
  'descuento': 'discount',
  'nuevo': 'new',
  'popular': 'popular',
  'recomendado': 'recommended',
  'exclusivo': 'exclusive',
  'limitado': 'limited',
  'temporada': 'seasonal',
  'orgánico': 'organic',
  'natural': 'natural',
  'fresco': 'fresh',
  'congelado': 'frozen',
  'enlatado': 'canned',
  'empacado': 'packaged',
  'granel': 'bulk',
  'unidad': 'unit',
  'paquete': 'package',
  'caja': 'box',
  'botella': 'bottle',
  'lata': 'can',
  'bolsa': 'bag',
  'kilo': 'kilo',
  'gramo': 'gram',
  'litro': 'liter',
  'mililitro': 'milliliter',
  'onza': 'ounce',
  'libra': 'pound',
  'galón': 'gallon',
  'docena': 'dozen',

  // Common product terms
  'arroz': 'rice',
  'atun': 'tuna',
  'atún': 'tuna',
  'leche': 'milk',
  'pan': 'bread',
  'queso': 'cheese',
  'pollo': 'chicken',
  'carne': 'meat',
  'pescado': 'fish',
  'frutas': 'fruits',
  'verduras': 'vegetables',
  'aceite': 'oil',
  'azucar': 'sugar',
  'azúcar': 'sugar',
  'sal': 'salt',
  'agua': 'water',
  'jugo': 'juice',
  'cafe': 'coffee',
  'café': 'coffee',
  'café frío': 'cold brew coffee',
  'capuccino_alt': 'cappuccino',
  'te': 'tea',
  'té': 'tea',
  'cerveza': 'beer',
  'vino': 'wine',
  'pasta': 'pasta',
  'frijoles': 'beans',
  'huevos': 'eggs',
  'mantequilla': 'butter',
  'yogurt': 'yogurt',
  'chocolate': 'chocolate',
  'galletas': 'cookies',
  'cereal': 'cereal',
  'salsa': 'sauce',
  'sopa': 'soup',
  'helado': 'ice cream',
  'manzana': 'apple',
  'banana': 'banana',
  'naranja': 'orange',
  'limón': 'lemon',
  'tomate': 'tomato',
  'papa': 'potato',
  'cebolla': 'onion',
  'ajo': 'garlic',
  'zanahoria': 'carrot',
  'lechuga': 'lettuce',
  'piña': 'pineapple',
  'sandía': 'watermelon',
  'melón': 'melon',
  'uva': 'grape',
  'fresa': 'strawberry',
  'aguacate': 'avocado',
  'pepino': 'cucumber',
  'pimiento': 'pepper',
  'maíz': 'corn',
  'jamón': 'ham',
  'salchicha': 'sausage',
  'tocino': 'bacon',
  'pavo': 'turkey',
  'res': 'beef',
  'cerdo': 'pork',
  'cordero': 'lamb',
  'camarón': 'shrimp',
  'salmón': 'salmon',
  'sardina': 'sardine',
  
  // Common brand terms
  'marca': 'brand',
  'precio': 'price',
  'tienda': 'store',
  'producto': 'product',
  'descripción': 'description',
  'añadir': 'add',
  'lista': 'list',
  'compras': 'shopping',
  'buscar': 'search',
  'resultados': 'results',
  'volver': 'back',
  'eliminar': 'remove',
  'guardar': 'save',
  'editar': 'edit',
  'compartir': 'share',
  'favorito': 'favorite',
  'calificación': 'rating',
  'comentario': 'comment',
  'reseña': 'review',
  'disponible': 'available',
  'agotado': 'sold out',
  'en stock': 'in stock',
  'cantidad': 'quantity',
  'total': 'total',
  'subtotal': 'subtotal',
  'impuesto': 'tax',
  'envío': 'shipping',
  'entrega': 'delivery',
  'recogida': 'pickup',
  'dirección': 'address',
  'pago': 'payment',
  'tarjeta': 'card',
  'efectivo': 'cash',
  'transferencia': 'transfer',
  'factura': 'invoice',
  'recibo': 'receipt',
  'pedido': 'order',
  'historial': 'history',
  'cuenta': 'account',
  'perfil': 'profile',
  'configuración': 'settings',
  'ayuda': 'help',
  'contacto': 'contact',
  'información': 'information',
  'términos': 'terms',
  'privacidad': 'privacy',
  'política': 'policy',
  'condiciones': 'conditions',
  'servicio': 'service',
  'cliente': 'customer',
  'usuario': 'user',
  'contraseña': 'password',
  'iniciar sesión': 'login',
  'registrarse': 'register',
  'cerrar sesión': 'logout',
  'olvidé mi contraseña': 'forgot my password',
  'recordarme': 'remember me',
  'verificación': 'verification',
  'código': 'code',
  'confirmar': 'confirm',
  'cancelar': 'cancel',
  'continuar': 'continue',
  'finalizar': 'finish',
  'siguiente': 'next',
  'anterior': 'previous',
  'primero': 'first',
  'último': 'last',
  'más': 'more',
  'menos': 'less',
  'todo': 'all',
  'nada': 'nothing',
  'sí': 'yes',
  'no': 'no',
  'aceptar': 'accept',
  'rechazar': 'reject',
  'aplicar': 'apply',
  'filtrar': 'filter',
  'ordenar': 'sort',
  'ascendente': 'ascending',
  'descendente': 'descending',
  'desde': 'from',
  'hasta': 'to',
  'entre': 'between',
  'con': 'with',
  'sin': 'without',
  'y': 'and',
  'o': 'or',
  'de': 'of',
  'en': 'in',
  'para': 'for',
  'por': 'by',
  'el': 'the',
  'la': 'the',
  'los': 'the',
  'las': 'the',
  'un': 'a',
  'una': 'a',
  'unos': 'some',
  'unas': 'some',
  'este': 'this',
  'esta': 'this',
  'estos': 'these',
  'estas': 'these',
  'ese': 'that',
  'esa': 'that',
  'esos': 'those',
  'esas': 'those',
  'mi': 'my',
  'mis': 'my',
  'tu': 'your',
  'tus': 'your',
  'su': 'their',
  'sus': 'their',
  'nuestro': 'our',
  'nuestra': 'our',
  'nuestros': 'our',
  'nuestras': 'our',
  'que': 'that',
  'cual': 'which',
  'quien': 'who',
  'donde': 'where',
  'cuando': 'when',
  'como': 'how',
  'por qué': 'why',
  'porque': 'because',
  'pero': 'but',
  'pues': 'well',
  'así': 'so',
  'también': 'also',
  'sin embargo': 'however',
  'no obstante': 'nevertheless',
  'aunque': 'although',
  'mientras': 'while',
  'durante': 'during',
  'después': 'after',
  'antes': 'before',
  'luego': 'then',
  'ahora': 'now',
  'hoy': 'today',
  'ayer': 'yesterday',
  'mañana': 'tomorrow',
  'siempre': 'always',
  'nunca': 'never',
  'jamás': 'never',
  'aquí': 'here',
  'allí': 'there',
  'allá': 'over there',
  'dentro': 'inside',
  'fuera': 'outside',
  'arriba': 'up',
  'abajo': 'down',
  'cerca': 'near',
  'lejos': 'far',
  'delante': 'in front',
  'detrás': 'behind',
  'sobre': 'on',
  'bajo': 'under',
  'junto': 'next to',
  'alrededor': 'around',
  'través': 'through',
  'hacia': 'towards',
  'según': 'according to',
  'excepto': 'except',
  'salvo': 'except for',
  'incluso': 'even',
  'asimismo': 'likewise',
  'igualmente': 'equally',
  'mejor': 'better',
  'peor': 'worse',
  'mayor': 'greater',
  'menor': 'lesser',
  'tan': 'so',
  'tanto': 'so much',
  'mucho': 'much',
  'poco': 'little',
  'bastante': 'quite',
  'demasiado': 'too much',
  'muy': 'very',
  'casi': 'almost',
  'aproximadamente': 'approximately',
  'exactamente': 'exactly',
  'solamente': 'only',
  'únicamente': 'solely',
  'principalmente': 'mainly',
  'especialmente': 'especially',
  'particularmente': 'particularly',
  'generalmente': 'generally',
  'usualmente': 'usually',
  'normalmente': 'normally',
  'regularmente': 'regularly',
  'frecuentemente': 'frequently',
  'ocasionalmente': 'occasionally',
  'raramente': 'rarely',
  'apenas': 'barely',
  'probablemente': 'probably',
  'posiblemente': 'possibly',
  'quizás': 'maybe',
  'tal vez': 'perhaps',
  'acaso': 'perhaps',
  'seguramente': 'surely',
  'ciertamente': 'certainly',
  'definitivamente': 'definitely',
  'absolutamente': 'absolutely',
  'completamente': 'completely',
  'totalmente': 'totally',
  'enteramente': 'entirely',
  'parcialmente': 'partially',
  'gradualmente': 'gradually',
  'progresivamente': 'progressively',
  'rápidamente': 'quickly',
  'lentamente': 'slowly',
  'suavemente': 'smoothly',
  'fuertemente': 'strongly',
  'débilmente': 'weakly',
  'fácilmente': 'easily',
  'difícilmente': 'hardly',
  'correctamente': 'correctly',
  'incorrectamente': 'incorrectly',
  'adecuadamente': 'adequately',
  'inadecuadamente': 'inadequately',
  'perfectamente': 'perfectly',
  'imperfectamente': 'imperfectly',
  'naturalmente': 'naturally',
  'artificialmente': 'artificially',
  'voluntariamente': 'voluntarily',
  'involuntariamente': 'involuntarily',
  'conscientemente': 'consciously',
  'inconscientemente': 'unconsciously',
  'automáticamente': 'automatically',
  'manualmente': 'manually',
  'personalmente': 'personally',
  'profesionalmente': 'professionally',
  'comercialmente': 'commercially',
  'industrialmente': 'industrially',
  'técnicamente': 'technically',
  'científicamente': 'scientifically',
  'teóricamente': 'theoretically',
  'prácticamente': 'practically',
  'económicamente': 'economically',
  'financieramente': 'financially',
  'socialmente': 'socially',
  'culturalmente': 'culturally',
  'políticamente': 'politically',
  'históricamente': 'historically',
  'tradicionalmente': 'traditionally',
  'modernamente': 'modernly',
  'actualmente': 'currently',
  'antiguamente': 'anciently',
  'previamente': 'previously',
  'posteriormente': 'subsequently',
  'finalmente': 'finally',
  'inicialmente': 'initially',
  'originalmente': 'originally',
  'eventualmente': 'eventually',
  'periódicamente': 'periodically',
  'temporalmente': 'temporarily',
  'permanentemente': 'permanently',
  'momentáneamente': 'momentarily',
  'instantáneamente': 'instantly',
  'inmediatamente': 'immediately',
  'mediatamente': 'mediately',
  'últimamente': 'lately',
  'recientemente': 'recently',
  'próximamente': 'soon',
  'temprano': 'early',
  'tarde': 'late',
  'despierta': 'awaken',
  'sentidos': 'senses',
  'irresistible': 'irresistible',
  'sabor': 'flavor',
  'experiencia': 'experience',
  'única': 'unique',
  'transformará': 'will transform',
  'mañanas': 'mornings',
  'dos': 'two',
  'pinos': 'pines',
  'frío': 'cold',
  'brew': 'brew',
  'cold brew': 'cold brew',
  'coffee': 'coffee',
  'cappuccino': 'cappuccino',
  'capuchino': 'cappuccino',
};

export async function POST(request: NextRequest) {
  try {
    const { text, from, to } = await request.json();
    
    // Return empty string if text is empty or null
    if (!text || text.trim() === '') {
      return NextResponse.json({ translatedText: '' });
    }
    
    if (!from || !to) {
      return NextResponse.json(
        { error: 'Missing required parameters' },
        { status: 400 }
      );
    }

    // Function to clean text for lookup
    const cleanText = (text: string) => text.toLowerCase().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, '');

    // Function to find translation for a phrase
    const findTranslation = (phrase: string, fromLang: string, toLang: string): string | null => {
      const cleanPhrase = cleanText(phrase);
      
      if (fromLang === 'es' && toLang === 'en') {
        return translations[cleanPhrase] || null;
      } else if (fromLang === 'en' && toLang === 'es') {
        for (const [spanish, english] of Object.entries(translations)) {
          if (cleanText(english) === cleanPhrase) {
            return spanish;
          }
        }
      }
      return null;
    };

    // Split text into words but preserve phrases
    const words = text.split(/\s+/);
    let translatedWords: string[] = [];
    
    // Try to translate longer phrases first
    for (let i = 0; i < words.length; i++) {
      let translated = false;
      
      // Try 3-word phrases
      if (i + 2 < words.length) {
        const threeWordPhrase = words.slice(i, i + 3).join(' ');
        const translation = findTranslation(threeWordPhrase, from, to);
        if (translation) {
          translatedWords.push(translation);
          i += 2;
          translated = true;
          continue;
        }
      }
      
      // Try 2-word phrases
      if (i + 1 < words.length) {
        const twoWordPhrase = words.slice(i, i + 2).join(' ');
        const translation = findTranslation(twoWordPhrase, from, to);
        if (translation) {
          translatedWords.push(translation);
          i += 1;
          translated = true;
          continue;
        }
      }
      
      // Try single words
      if (!translated) {
        const translation = findTranslation(words[i], from, to);
        translatedWords.push(translation || words[i]);
      }
    }
    
    // Join the translated words back together
    const translatedText = translatedWords.join(' ');
    
    // Capitalize the first letter if the original text started with a capital
    const finalText = text[0] === text[0].toUpperCase() 
      ? translatedText.charAt(0).toUpperCase() + translatedText.slice(1)
      : translatedText;
    
    return NextResponse.json({ translatedText: finalText });
  } catch (error) {
    console.error('Translation error:', error);
    return NextResponse.json(
      { error: 'Failed to translate text' },
      { status: 500 }
    );
  }
} 